In [1]:
import numpy as np

In [2]:
list1 = [1,200,45,66]

list1

[1, 200, 45, 66]

In [3]:
#make an array of this list

arr1 = np.array(list1)

arr1

array([  1, 200,  45,  66])

In [8]:
list_of_lists = [[200,44,33,21,88],[23,54,33,22,11],[123,456,789,344,90]]

list_of_lists

[[200, 44, 33, 21, 88], [23, 54, 33, 22, 11], [123, 456, 789, 344, 90]]

In [9]:
arr2 = np.array(list_of_lists)

arr2

array([[200,  44,  33,  21,  88],
       [ 23,  54,  33,  22,  11],
       [123, 456, 789, 344,  90]])

In [11]:
array_of_zeroes = np.zeros(3)

array_of_zeroes

array([0., 0., 0.])

In [12]:
array_of_ones = np.ones(25)

array_of_ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
arr3 = np.ones((4,6))

arr3

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [15]:
arr4 = np.zeros((5,9))

In [16]:
arr4

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])